[gitlab]
# gitlab domain, like https://gitlab.com
base_url = "$GITLAB_BASE_URL"

# gitlab access token
token = "$GITLAB_TOKEN"

# gitlab projects file
# default $HOME/config/.lab/.projects
projects = ""

# If set, lab clone and lab ws will use this path as target path
# default empty
codespace = ""

# If set, lab clone will auto set user.name in repo gitconfig
# default empty
name = ""

# If set, lab clone will auto set user.email in repo gitconfig
# default empty
email = ""

[main]
# If set 1, it will use fzf as fuzzy finder, default use go-fuzzyfinder
# default 0
fzf = 0

# lab clone extra custom git clone config
# example `clone_opts="--origin ackerr --branch fix"`
# default empty
clone_opts = ""
